#define MORSE

#define Di ((char)1)
#define Da ((char)0)
#define Pause ((char)2)

#define morseA ((char[]){Di,Da})
#define morseB ((char[]){Da,Di,Di,Di})
#define morseC ((char[]){Da,Di,Da,Di})
#define morseD ((char[]){Da,Di,Di})
#define morseE ((char[]){Di})
#define morseF ((char[]){Di,Di,Da,Di})
#define morseG ((char[]){Da,Da,Di})
#define morseH ((char[]){Di,Di,Di,Di})
#define morseI ((char[]){Di,Di})
#define morseJ ((char[]){Di,Da,Da,Da})
#define morseK ((char[]){Da,Di,Da})
#define morseL ((char[]){Di,Da,Di,Di})
#define morseM ((char[]){Da,Da})
#define morseN ((char[]){Da,Di})
#define morseO ((char[]){Da,Da,Da})
#define morseP ((char[]){Di,Da,Da,Di})
#define morseQ ((char[]){Da,Da,Di,Da})
#define morseR ((char[]){Di,Da,Di})
#define morseS ((char[]){Di,Di,Di})
#define morseT ((char[]){Da})
#define morseU ((char[]){Di,Di,Da})
#define morseV ((char[]){Di,Di,Di,Da})
#define morseW ((char[]){Di,Da,Da})
#define morseX ((char[]){Da,Di,Di,Da})
#define morseY ((char[]){Da,Di,Da,Da})
#define morseZ ((char[]){Da,Da,Di,Di})
#define morse0 ((char[]){Da,Da,Da,Da,Da})
#define morse1 ((char[]){Di,Da,Da,Da,Da})
#define morse2 ((char[]){Di,Di,Da,Da,Da})
#define morse3 ((char[]){Di,Di,Di,Da,Da})
#define morse4 ((char[]){Di,Di,Di,Di,Da})
#define morse5 ((char[]){Di,Di,Di,Di,Di})
#define morse6 ((char[]){Da,Di,Di,Di,Di})
#define morse7 ((char[]){Da,Da,Di,Di,Di})
#define morse8 ((char[]){Da,Da,Da,Di,Di})
#define morse9 ((char[]){Da,Da,Da,Da,Di})





